name: CI (diagnostic-smoke)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  win:
    name: windows-smoke
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment dump
        run: |
          $PSVersionTable
          Get-Location
          Write-Host "Workspace: $env:GITHUB_WORKSPACE"
          git --version
          Get-ChildItem -Recurse -File | Select-Object -First 200 FullName | Format-Table -Auto

      - name: Ensure TLS + PSGallery + Pester
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Set-PSRepository PSGallery -InstallationPolicy Trusted -ErrorAction SilentlyContinue
          try {
            Import-Module Pester -MinimumVersion 5.0 -ErrorAction Stop
          } catch {
            Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck -ErrorAction Stop
            Import-Module Pester -MinimumVersion 5.0 -ErrorAction Stop
          }

      - name: Import PSAdminToolkit (debug)
        run: |
          Import-Module ./src/PSAdminToolkit/PSAdminToolkit.psd1 -Force -Verbose
          Get-Command -Module PSAdminToolkit | Format-Table Name, CommandType

      - name: Run Pester tests (explicit path)
        run: Invoke-Pester -CI -Path tests/PSAdminToolkit.Tests.ps1 -Output Detailed