name: CI (smoke)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pester:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use PowerShell 7.4
        uses: actions/setup-powershell@v2
        with:
          pwsh-version: '7.4.x'

      - name: Run Pester tests (auto-install if missing)
        run: |
          try {
            Import-Module Pester -MinimumVersion 5.0 -ErrorAction Stop
          } catch {
            Write-Host "Pester not found. Installing..." 
            Set-PSRepository PSGallery -InstallationPolicy Trusted -ErrorAction SilentlyContinue
            Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck -ErrorAction Stop
            Import-Module Pester -MinimumVersion 5.0 -ErrorAction Stop
          }
          Invoke-Pester -CI -Output Detailed