name: CI

on:
  push:
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer & Pester
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force -AllowClobber
          Install-Module Pester -Scope CurrentUser -Force -AllowClobber

      - name: Script Analyzer
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path src -Recurse -Settings ./tools/PSScriptAnalyzerSettings.psd1 -Verbose:$false -Severity Error
          if ($results) {
            $results | Format-Table
            throw "PSScriptAnalyzer found errors."
          }

      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -CI -Output Detailed
